/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

/**
 *
 * @author mihajlo
 */
public class KreirajRezervacijaForm extends javax.swing.JFrame {

    /**
     * Creates new form KreirajRezervacijaForm
     */
    public KreirajRezervacijaForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgent = new javax.swing.JLabel();
        cmbAgent = new javax.swing.JComboBox<>();
        lblPutnik = new javax.swing.JLabel();
        cmbPutnik = new javax.swing.JComboBox<>();
        lblStatusPlacanja = new javax.swing.JLabel();
        cmbStatusPlacanja = new javax.swing.JComboBox<>(new String[]{"Ceka", "Placeno"});
        lblNapomena = new javax.swing.JLabel();
        txtNapomena = new javax.swing.JTextField();
        lblAranzman = new javax.swing.JLabel();
        cmbAranzman = new javax.swing.JComboBox<>();
        lblBrojOsoba = new javax.swing.JLabel();
        txtBrojOsoba = new javax.swing.JTextField();
        lblDatumPolaska = new javax.swing.JLabel();
        txtDatumPolaska = new javax.swing.JTextField();
        lblDatumDolaska = new javax.swing.JLabel();
        txtDatumDolaska = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        scrollTabelaStavki = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnUkloniStavku = new javax.swing.JButton();
        btnSacuvajRezervaciju = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Туристичка агенција - Креирај резервацију");

        lblAgent.setText("Агент:");

        lblPutnik.setText("Путник:");

        lblStatusPlacanja.setText("Статус плаћања:");

        lblNapomena.setText("Напомена:");

        lblAranzman.setText("Аранжман:");

        lblBrojOsoba.setText("Број особа:");

        lblDatumPolaska.setText("Датум поласка (dd.MM.yyyy):");

        lblDatumDolaska.setText("Датум доласка (dd.MM.yyyy):");

        btnDodajStavku.setText("Додај ставку");

        scrollTabelaStavki.setViewportView(tblStavke);

        btnUkloniStavku.setText("Уклони ставку");

        btnSacuvajRezervaciju.setText("Сачувај резервацију");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabelaStavki, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgent)
                            .addComponent(lblPutnik)
                            .addComponent(lblStatusPlacanja)
                            .addComponent(lblNapomena)
                            .addComponent(lblAranzman)
                            .addComponent(lblBrojOsoba)
                            .addComponent(lblDatumPolaska)
                            .addComponent(lblDatumDolaska))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAgent, 0, 400, Short.MAX_VALUE)
                            .addComponent(cmbPutnik, 0, 400, Short.MAX_VALUE)
                            .addComponent(cmbStatusPlacanja, 0, 400, Short.MAX_VALUE)
                            .addComponent(txtNapomena)
                            .addComponent(cmbAranzman, 0, 400, Short.MAX_VALUE)
                            .addComponent(txtBrojOsoba)
                            .addComponent(txtDatumPolaska)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDatumDolaska, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDodajStavku))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUkloniStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSacuvajRezervaciju)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgent)
                    .addComponent(cmbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPutnik)
                    .addComponent(cmbPutnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusPlacanja)
                    .addComponent(cmbStatusPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNapomena)
                    .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAranzman)
                    .addComponent(cmbAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojOsoba)
                    .addComponent(txtBrojOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumPolaska)
                    .addComponent(txtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumDolaska)
                    .addComponent(txtDatumDolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabelaStavki, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUkloniStavku)
                    .addComponent(btnSacuvajRezervaciju))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnSacuvajRezervaciju;
    private javax.swing.JButton btnUkloniStavku;
    private javax.swing.JComboBox<domain.Agent> cmbAgent;
    private javax.swing.JComboBox<domain.Aranzman> cmbAranzman;
    private javax.swing.JComboBox<domain.Putnik> cmbPutnik;
    private javax.swing.JComboBox<java.lang.String> cmbStatusPlacanja;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblAranzman;
    private javax.swing.JLabel lblBrojOsoba;
    private javax.swing.JLabel lblDatumDolaska;
    private javax.swing.JLabel lblDatumPolaska;
    private javax.swing.JLabel lblNapomena;
    private javax.swing.JLabel lblPutnik;
    private javax.swing.JLabel lblStatusPlacanja;
    private javax.swing.JScrollPane scrollTabelaStavki;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojOsoba;
    private javax.swing.JTextField txtDatumDolaska;
    private javax.swing.JTextField txtDatumPolaska;
    private javax.swing.JTextField txtNapomena;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<domain.Agent> getCmbAgent() {
        return cmbAgent;
    }

    public javax.swing.JComboBox<domain.Putnik> getCmbPutnik() {
        return cmbPutnik;
    }

    public javax.swing.JComboBox<java.lang.String> getCmbStatusPlacanja() {
        return cmbStatusPlacanja;
    }

    public javax.swing.JTextField getTxtNapomena() {
        return txtNapomena;
    }

    public javax.swing.JComboBox<domain.Aranzman> getCmbAranzman() {
        return cmbAranzman;
    }

    public javax.swing.JTextField getTxtBrojOsoba() {
        return txtBrojOsoba;
    }

    public javax.swing.JTextField getTxtDatumPolaska() {
        return txtDatumPolaska;
    }

    public javax.swing.JTextField getTxtDatumDolaska() {
        return txtDatumDolaska;
    }

    public javax.swing.JButton getBtnDodajStavku() {
        return btnDodajStavku;
    }

    public javax.swing.JTable getTblStavke() {
        return tblStavke;
    }

    public javax.swing.JButton getBtnUkloniStavku() {
        return btnUkloniStavku;
    }

    public javax.swing.JButton getBtnSacuvajRezervaciju() {
        return btnSacuvajRezervaciju;
    }
}
