/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

import javax.swing.JFrame;

/**
 *
 * @author mihajlo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        lblAgent = new javax.swing.JLabel();
        btnOProgramu = new javax.swing.JButton();
        pnlRezervacije = new javax.swing.JPanel();
        btnKreirajRezervaciju = new javax.swing.JButton();
        btnPretraziRezervaciju = new javax.swing.JButton();
        pnlPutnici = new javax.swing.JPanel();
        btnKreirajPutnika = new javax.swing.JButton();
        btnPretraziPutnika = new javax.swing.JButton();
        pnlRegioni = new javax.swing.JPanel();
        btnUbaciRegion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turistička agencija");

        lblNaslov.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblNaslov.setText("Turistička agencija");

        lblAgent.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAgent.setText("Agent: -");

        btnOProgramu.setText("O programu");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addGap(0, 186, Short.MAX_VALUE)
                .addComponent(lblAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOProgramu)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaslov)
                    .addComponent(lblAgent)
                    .addComponent(btnOProgramu))
                .addContainerGap())
        );

        pnlRezervacije.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacije"));

        btnKreirajRezervaciju.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKreirajRezervaciju.setText("🧳  Kreiraj rezervaciju");

        btnPretraziRezervaciju.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPretraziRezervaciju.setText("🔍  Pretraži rezervaciju");

        javax.swing.GroupLayout pnlRezervacijeLayout = new javax.swing.GroupLayout(pnlRezervacije);
        pnlRezervacije.setLayout(pnlRezervacijeLayout);
        pnlRezervacijeLayout.setHorizontalGroup(
            pnlRezervacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRezervacijeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKreirajRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretraziRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRezervacijeLayout.setVerticalGroup(
            pnlRezervacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRezervacijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRezervacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlPutnici.setBorder(javax.swing.BorderFactory.createTitledBorder("Putnici"));

        btnKreirajPutnika.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKreirajPutnika.setText("🧑  Kreiraj putnika");

        btnPretraziPutnika.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPretraziPutnika.setText("🔍  Pretraži putnika");

        javax.swing.GroupLayout pnlPutniciLayout = new javax.swing.GroupLayout(pnlPutnici);
        pnlPutnici.setLayout(pnlPutniciLayout);
        pnlPutniciLayout.setHorizontalGroup(
            pnlPutniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPutniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKreirajPutnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretraziPutnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPutniciLayout.setVerticalGroup(
            pnlPutniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPutniciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPutniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRegioni.setBorder(javax.swing.BorderFactory.createTitledBorder("Regioni"));

        btnUbaciRegion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUbaciRegion.setText("🌍  Ubaci region");

        javax.swing.GroupLayout pnlRegioniLayout = new javax.swing.GroupLayout(pnlRegioni);
        pnlRegioni.setLayout(pnlRegioniLayout);
        pnlRegioniLayout.setHorizontalGroup(
            pnlRegioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegioniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUbaciRegion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRegioniLayout.setVerticalGroup(
            pnlRegioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegioniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUbaciRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPutnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRegioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPutnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajPutnika;
    private javax.swing.JButton btnKreirajRezervaciju;
    private javax.swing.JButton btnOProgramu;
    private javax.swing.JButton btnPretraziPutnika;
    private javax.swing.JButton btnPretraziRezervaciju;
    private javax.swing.JButton btnUbaciRegion;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPutnici;
    private javax.swing.JPanel pnlRegioni;
    private javax.swing.JPanel pnlRezervacije;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnKreirajRezervaciju() {
        return btnKreirajRezervaciju;
    }

    public javax.swing.JButton getBtnPretraziRezervaciju() {
        return btnPretraziRezervaciju;
    }

    public javax.swing.JButton getBtnKreirajPutnika() {
        return btnKreirajPutnika;
    }

    public javax.swing.JButton getBtnPretraziPutnika() {
        return btnPretraziPutnika;
    }

    public javax.swing.JButton getBtnUbaciRegion() {
        return btnUbaciRegion;
    }

    public javax.swing.JButton getBtnOProgramu() {
        return btnOProgramu;
    }

    public javax.swing.JLabel getLblAgent() {
        return lblAgent;
    }
}
