/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

import javax.swing.JFrame;

/**
 *
 * @author mihajlo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        new MainController(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuDokumenti = new javax.swing.JMenu();
        menuRezervacija = new javax.swing.JMenu();
        miKreirajRezervaciju = new javax.swing.JMenuItem();
        miPretraziRezervaciju = new javax.swing.JMenuItem();
        menuPruzalacUsluge = new javax.swing.JMenu();
        miAgent = new javax.swing.JMenuItem();
        menuPrimalacUsluge = new javax.swing.JMenu();
        menuPutnik = new javax.swing.JMenu();
        miKreirajPutnika = new javax.swing.JMenuItem();
        miPretraziPutnika = new javax.swing.JMenuItem();
        menuSifarnici = new javax.swing.JMenu();
        miAranzman = new javax.swing.JMenuItem();
        miMesto = new javax.swing.JMenuItem();
        miRegion = new javax.swing.JMenuItem();
        miPodesavanja = new javax.swing.JMenuItem();
        miOProgramu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turistička agencija");

        menuDokumenti.setText("Dokumenti");

        menuRezervacija.setText("Rezervacija");

        miKreirajRezervaciju.setText("Kreiraj rezervaciju");
        menuRezervacija.add(miKreirajRezervaciju);

        miPretraziRezervaciju.setText("Pretraži rezervaciju");
        menuRezervacija.add(miPretraziRezervaciju);

        menuDokumenti.add(menuRezervacija);

        menuBar.add(menuDokumenti);

        menuPruzalacUsluge.setText("Pružalac usluge");

        miAgent.setText("Agent");
        miAgent.setEnabled(false);
        menuPruzalacUsluge.add(miAgent);

        menuBar.add(menuPruzalacUsluge);

        menuPrimalacUsluge.setText("Primalac usluge");

        menuPutnik.setText("Putnik");

        miKreirajPutnika.setText("Kreiraj putnika");
        menuPutnik.add(miKreirajPutnika);

        miPretraziPutnika.setText("Pretraži putnika");
        menuPutnik.add(miPretraziPutnika);

        menuPrimalacUsluge.add(menuPutnik);

        menuBar.add(menuPrimalacUsluge);

        menuSifarnici.setText("Šifarnici");

        miAranzman.setText("Aranžman");
        miAranzman.setEnabled(false);
        menuSifarnici.add(miAranzman);

        miMesto.setText("Mesto");
        miMesto.setEnabled(false);
        menuSifarnici.add(miMesto);

        miRegion.setText("Ubaci region");
        menuSifarnici.add(miRegion);

        menuBar.add(menuSifarnici);

        miPodesavanja.setText("Podešavanja softverskog sistema");
        miPodesavanja.setEnabled(false);
        menuBar.add(miPodesavanja);

        miOProgramu.setText("O programu");
        menuBar.add(miOProgramu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDokumenti;
    private javax.swing.JMenuItem miAgent;
    private javax.swing.JMenuItem miAranzman;
    private javax.swing.JMenuItem miKreirajPutnika;
    private javax.swing.JMenuItem miKreirajRezervaciju;
    private javax.swing.JMenuItem miMesto;
    private javax.swing.JMenuItem miOProgramu;
    private javax.swing.JMenuItem miPodesavanja;
    private javax.swing.JMenuItem miPretraziPutnika;
    private javax.swing.JMenuItem miPretraziRezervaciju;
    private javax.swing.JMenuItem miRegion;
    private javax.swing.JMenu menuPrimalacUsluge;
    private javax.swing.JMenu menuPruzalacUsluge;
    private javax.swing.JMenu menuPutnik;
    private javax.swing.JMenu menuRezervacija;
    private javax.swing.JMenu menuSifarnici;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getMiKreirajRezervaciju() {
        return miKreirajRezervaciju;
    }

    public javax.swing.JMenuItem getMiPretraziRezervaciju() {
        return miPretraziRezervaciju;
    }

    public javax.swing.JMenuItem getMiKreirajPutnika() {
        return miKreirajPutnika;
    }

    public javax.swing.JMenuItem getMiPretraziPutnika() {
        return miPretraziPutnika;
    }

    public javax.swing.JMenuItem getMiRegion() {
        return miRegion;
    }

    public javax.swing.JMenuItem getMiOProgramu() {
        return miOProgramu;
    }
}
