/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

/**
 *
 * @author mihajlo
 */
public class OProgramuForm extends javax.swing.JFrame {

    /**
     * Creates new form OProgramuForm
     */
    public OProgramuForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUniverzitet = new javax.swing.JLabel();
        lblFakultet = new javax.swing.JLabel();
        lblKatedra = new javax.swing.JLabel();
        sepGore = new javax.swing.JSeparator();
        lblSeminarski = new javax.swing.JLabel();
        lblPredmet = new javax.swing.JLabel();
        lblNaslovProjekta1 = new javax.swing.JLabel();
        lblNaslovProjekta2 = new javax.swing.JLabel();
        sepDole = new javax.swing.JSeparator();
        lblMentorLabel = new javax.swing.JLabel();
        lblMentorIme = new javax.swing.JLabel();
        lblStudentLabel = new javax.swing.JLabel();
        lblStudentIme = new javax.swing.JLabel();
        lblBrojIndeksaLabel = new javax.swing.JLabel();
        lblBrojIndeksaVrednost = new javax.swing.JLabel();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("О програму");
        setResizable(false);

        lblUniverzitet.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblUniverzitet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniverzitet.setText("Универзитет у Београду");

        lblFakultet.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblFakultet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFakultet.setText("Факултет организационих наука");

        lblKatedra.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblKatedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKatedra.setText("Катедра за софтверско инжењерство");

        lblSeminarski.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblSeminarski.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeminarski.setText("Семинарски рад из предмета");

        lblPredmet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPredmet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPredmet.setText("Пројектовање софтвера");

        lblNaslovProjekta1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblNaslovProjekta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslovProjekta1.setText("Софтверски систем за управљање резервацијама");

        lblNaslovProjekta2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblNaslovProjekta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslovProjekta2.setText("туристичке агенције у Јава окружењу");

        lblMentorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMentorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMentorLabel.setText("Ментор:");

        lblMentorIme.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblMentorIme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMentorIme.setText("проф. др Синиша Влајић");

        lblStudentLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentLabel.setText("Студент:");

        lblStudentIme.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblStudentIme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentIme.setText("Михајло Ранђеловић");

        lblBrojIndeksaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBrojIndeksaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrojIndeksaLabel.setText("Број индекса:");

        lblBrojIndeksaVrednost.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblBrojIndeksaVrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrojIndeksaVrednost.setText("2023/0206");

        btnZatvori.setText("Затвори");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUniverzitet, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblFakultet, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblKatedra, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(sepGore, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblSeminarski, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblPredmet, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblNaslovProjekta1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblNaslovProjekta2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(sepDole, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblMentorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblMentorIme, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblStudentIme, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblBrojIndeksaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(lblBrojIndeksaVrednost, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(btnZatvori))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUniverzitet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFakultet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKatedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepGore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeminarski)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPredmet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNaslovProjekta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNaslovProjekta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepDole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMentorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMentorIme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStudentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentIme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBrojIndeksaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrojIndeksaVrednost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZatvori)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel lblBrojIndeksaLabel;
    private javax.swing.JLabel lblBrojIndeksaVrednost;
    private javax.swing.JLabel lblFakultet;
    private javax.swing.JLabel lblKatedra;
    private javax.swing.JLabel lblMentorIme;
    private javax.swing.JLabel lblMentorLabel;
    private javax.swing.JLabel lblNaslovProjekta1;
    private javax.swing.JLabel lblNaslovProjekta2;
    private javax.swing.JLabel lblPredmet;
    private javax.swing.JLabel lblSeminarski;
    private javax.swing.JLabel lblStudentIme;
    private javax.swing.JLabel lblStudentLabel;
    private javax.swing.JLabel lblUniverzitet;
    private javax.swing.JSeparator sepDole;
    private javax.swing.JSeparator sepGore;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnZatvori() {
        return btnZatvori;
    }
}
