/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

/**
 *
 * @author mihajlo
 */
public class PretraziRezervacijaForm extends javax.swing.JFrame {

    /**
     * Creates new form PretraziRezervacijaForm
     */
    public PretraziRezervacijaForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        txtStatusKriterijum = new javax.swing.JTextField();
        btnPretraziStatus = new javax.swing.JButton();
        lblAgentKriterijum = new javax.swing.JLabel();
        cmbAgentKriterijum = new javax.swing.JComboBox<>();
        btnPretraziAgent = new javax.swing.JButton();
        lblPutnikKriterijum = new javax.swing.JLabel();
        cmbPutnikKriterijum = new javax.swing.JComboBox<>();
        btnPretraziPutnik = new javax.swing.JButton();
        lblAranzmanKriterijum = new javax.swing.JLabel();
        cmbAranzmanKriterijum = new javax.swing.JComboBox<>();
        btnPretraziAranzman = new javax.swing.JButton();
        scrollTabelaRezervacije = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        btnPrikazi = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        scrollDetalji = new javax.swing.JScrollPane();
        txtAreaDetalji = new javax.swing.JTextArea();
        scrollTabelaStavki = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Туристичка агенција - Претражи резервацију");

        lblStatus.setText("Статус плаћања:");

        btnPretraziStatus.setText("Претражи по статусу");

        lblAgentKriterijum.setText("Агент:");

        btnPretraziAgent.setText("Претражи по агенту");

        lblPutnikKriterijum.setText("Путник:");

        btnPretraziPutnik.setText("Претражи по путнику");

        lblAranzmanKriterijum.setText("Аранжман:");

        btnPretraziAranzman.setText("Претражи по аранжману");

        scrollTabelaRezervacije.setViewportView(tblRezervacije);

        btnPrikazi.setText("Прикажи детаље");

        btnPromeni.setText("Промени");

        txtAreaDetalji.setEditable(false);
        txtAreaDetalji.setColumns(20);
        txtAreaDetalji.setRows(4);
        scrollDetalji.setViewportView(txtAreaDetalji);

        scrollTabelaStavki.setViewportView(tblStavke);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabelaRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(scrollDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(scrollTabelaStavki, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatusKriterijum, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgentKriterijum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAgentKriterijum, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPutnikKriterijum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPutnikKriterijum, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziPutnik))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAranzmanKriterijum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAranzmanKriterijum, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziAranzman))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrikazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatusKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentKriterijum)
                    .addComponent(cmbAgentKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPutnikKriterijum)
                    .addComponent(cmbPutnikKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPutnik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAranzmanKriterijum)
                    .addComponent(cmbAranzmanKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziAranzman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabelaRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(btnPromeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabelaStavki, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziAgent;
    private javax.swing.JButton btnPretraziAranzman;
    private javax.swing.JButton btnPretraziPutnik;
    private javax.swing.JButton btnPretraziStatus;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<domain.Agent> cmbAgentKriterijum;
    private javax.swing.JComboBox<domain.Aranzman> cmbAranzmanKriterijum;
    private javax.swing.JComboBox<domain.Putnik> cmbPutnikKriterijum;
    private javax.swing.JLabel lblAgentKriterijum;
    private javax.swing.JLabel lblAranzmanKriterijum;
    private javax.swing.JLabel lblPutnikKriterijum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JScrollPane scrollDetalji;
    private javax.swing.JScrollPane scrollTabelaRezervacije;
    private javax.swing.JScrollPane scrollTabelaStavki;
    private javax.swing.JTable tblRezervacije;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextArea txtAreaDetalji;
    private javax.swing.JTextField txtStatusKriterijum;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtStatusKriterijum() {
        return txtStatusKriterijum;
    }

    public javax.swing.JButton getBtnPretraziStatus() {
        return btnPretraziStatus;
    }

    public javax.swing.JComboBox<domain.Agent> getCmbAgentKriterijum() {
        return cmbAgentKriterijum;
    }

    public javax.swing.JButton getBtnPretraziAgent() {
        return btnPretraziAgent;
    }

    public javax.swing.JComboBox<domain.Putnik> getCmbPutnikKriterijum() {
        return cmbPutnikKriterijum;
    }

    public javax.swing.JButton getBtnPretraziPutnik() {
        return btnPretraziPutnik;
    }

    public javax.swing.JComboBox<domain.Aranzman> getCmbAranzmanKriterijum() {
        return cmbAranzmanKriterijum;
    }

    public javax.swing.JButton getBtnPretraziAranzman() {
        return btnPretraziAranzman;
    }

    public javax.swing.JTable getTblRezervacije() {
        return tblRezervacije;
    }

    public javax.swing.JButton getBtnPrikazi() {
        return btnPrikazi;
    }

    public javax.swing.JButton getBtnPromeni() {
        return btnPromeni;
    }

    public javax.swing.JTextArea getTxtAreaDetalji() {
        return txtAreaDetalji;
    }

    public javax.swing.JTable getTblStavke() {
        return tblStavke;
    }
}
