/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view.form;

/**
 *
 * @author mihajlo
 */
public class PretraziRezervacijaForm extends javax.swing.JFrame {

    /**
     * Creates new form PretraziRezervacijaForm
     */
    public PretraziRezervacijaForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKriterijumi = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        cmbStatusKriterijum = new javax.swing.JComboBox<>(new String[]{"", "Плаћено", "На чекању"});
        lblAgentKriterijum = new javax.swing.JLabel();
        cmbAgentKriterijum = new javax.swing.JComboBox<>();
        lblPutnikKriterijum = new javax.swing.JLabel();
        cmbPutnikKriterijum = new javax.swing.JComboBox<>();
        lblAranzmanKriterijum = new javax.swing.JLabel();
        cmbAranzmanKriterijum = new javax.swing.JComboBox<>();
        lblIznosOd = new javax.swing.JLabel();
        txtIznosOd = new javax.swing.JTextField();
        lblIznosDo = new javax.swing.JLabel();
        txtIznosDo = new javax.swing.JTextField();
        lblDatumOd = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JTextField();
        lblDatumDo = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        scrollTabelaRezervacije = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        btnPrikazi = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        pnlInformacije = new javax.swing.JPanel();
        scrollDetalji = new javax.swing.JScrollPane();
        txtAreaDetalji = new javax.swing.JTextArea();
        pnlStavke = new javax.swing.JPanel();
        scrollTabelaStavki = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Туристичка агенција - Претражи резервацију");

        pnlKriterijumi.setBorder(javax.swing.BorderFactory.createTitledBorder("Критеријуми претраге"));

        lblStatus.setText("Статус плаћања:");

        lblAgentKriterijum.setText("Агент:");

        lblPutnikKriterijum.setText("Путник:");

        lblAranzmanKriterijum.setText("Аранжман:");

        lblIznosOd.setText("Износ од:");

        lblIznosDo.setText("Износ до:");

        lblDatumOd.setText("Датум од (dd.MM.yyyy):");

        lblDatumDo.setText("Датум до (dd.MM.yyyy):");

        btnPretrazi.setText("Претражи");

        javax.swing.GroupLayout pnlKriterijumiLayout = new javax.swing.GroupLayout(pnlKriterijumi);
        pnlKriterijumi.setLayout(pnlKriterijumiLayout);
        pnlKriterijumiLayout.setHorizontalGroup(
            pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKriterijumiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKriterijumiLayout.createSequentialGroup()
                        .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblAgentKriterijum)
                            .addComponent(lblPutnikKriterijum)
                            .addComponent(lblAranzmanKriterijum)
                            .addComponent(lblIznosOd)
                            .addComponent(lblIznosDo)
                            .addComponent(lblDatumOd)
                            .addComponent(lblDatumDo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatusKriterijum, 0, 300, Short.MAX_VALUE)
                            .addComponent(cmbAgentKriterijum, 0, 300, Short.MAX_VALUE)
                            .addComponent(cmbPutnikKriterijum, 0, 300, Short.MAX_VALUE)
                            .addComponent(cmbAranzmanKriterijum, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtIznosOd)
                            .addComponent(txtIznosDo)
                            .addComponent(txtDatumOd)
                            .addComponent(txtDatumDo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKriterijumiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPretrazi)))
                .addContainerGap())
        );
        pnlKriterijumiLayout.setVerticalGroup(
            pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKriterijumiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatusKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentKriterijum)
                    .addComponent(cmbAgentKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPutnikKriterijum)
                    .addComponent(cmbPutnikKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAranzmanKriterijum)
                    .addComponent(cmbAranzmanKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznosOd)
                    .addComponent(txtIznosOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznosDo)
                    .addComponent(txtIznosDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumOd)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKriterijumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumDo)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretrazi)
                .addContainerGap())
        );

        scrollTabelaRezervacije.setViewportView(tblRezervacije);

        btnPrikazi.setText("Прикажи детаље");

        btnPromeni.setText("Промени");

        pnlInformacije.setBorder(javax.swing.BorderFactory.createTitledBorder("Информације о резервацији"));

        txtAreaDetalji.setEditable(false);
        txtAreaDetalji.setColumns(20);
        txtAreaDetalji.setRows(4);
        scrollDetalji.setViewportView(txtAreaDetalji);

        javax.swing.GroupLayout pnlInformacijeLayout = new javax.swing.GroupLayout(pnlInformacije);
        pnlInformacije.setLayout(pnlInformacijeLayout);
        pnlInformacijeLayout.setHorizontalGroup(
            pnlInformacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacijeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDetalji)
                .addContainerGap())
        );
        pnlInformacijeLayout.setVerticalGroup(
            pnlInformacijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacijeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDetalji)
                .addContainerGap())
        );

        pnlStavke.setBorder(javax.swing.BorderFactory.createTitledBorder("Ставке резервације"));

        scrollTabelaStavki.setViewportView(tblStavke);

        javax.swing.GroupLayout pnlStavkeLayout = new javax.swing.GroupLayout(pnlStavke);
        pnlStavke.setLayout(pnlStavkeLayout);
        pnlStavkeLayout.setHorizontalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabelaStavki)
                .addContainerGap())
        );
        pnlStavkeLayout.setVerticalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabelaStavki)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlKriterijumi, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(scrollTabelaRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(pnlInformacije, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(pnlStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrikazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlKriterijumi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabelaRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(btnPromeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInformacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<domain.Agent> cmbAgentKriterijum;
    private javax.swing.JComboBox<domain.Aranzman> cmbAranzmanKriterijum;
    private javax.swing.JComboBox<domain.Putnik> cmbPutnikKriterijum;
    private javax.swing.JComboBox<java.lang.String> cmbStatusKriterijum;
    private javax.swing.JLabel lblAgentKriterijum;
    private javax.swing.JLabel lblAranzmanKriterijum;
    private javax.swing.JLabel lblDatumDo;
    private javax.swing.JLabel lblDatumOd;
    private javax.swing.JLabel lblIznosDo;
    private javax.swing.JLabel lblIznosOd;
    private javax.swing.JLabel lblPutnikKriterijum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlInformacije;
    private javax.swing.JPanel pnlKriterijumi;
    private javax.swing.JPanel pnlStavke;
    private javax.swing.JScrollPane scrollDetalji;
    private javax.swing.JScrollPane scrollTabelaRezervacije;
    private javax.swing.JScrollPane scrollTabelaStavki;
    private javax.swing.JTable tblRezervacije;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextArea txtAreaDetalji;
    private javax.swing.JTextField txtDatumDo;
    private javax.swing.JTextField txtDatumOd;
    private javax.swing.JTextField txtIznosDo;
    private javax.swing.JTextField txtIznosOd;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<java.lang.String> getCmbStatusKriterijum() {
        return cmbStatusKriterijum;
    }

    public javax.swing.JComboBox<domain.Agent> getCmbAgentKriterijum() {
        return cmbAgentKriterijum;
    }

    public javax.swing.JComboBox<domain.Putnik> getCmbPutnikKriterijum() {
        return cmbPutnikKriterijum;
    }

    public javax.swing.JComboBox<domain.Aranzman> getCmbAranzmanKriterijum() {
        return cmbAranzmanKriterijum;
    }

    public javax.swing.JTextField getTxtIznosOd() {
        return txtIznosOd;
    }

    public javax.swing.JTextField getTxtIznosDo() {
        return txtIznosDo;
    }

    public javax.swing.JTextField getTxtDatumOd() {
        return txtDatumOd;
    }

    public javax.swing.JTextField getTxtDatumDo() {
        return txtDatumDo;
    }

    public javax.swing.JButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public javax.swing.JTable getTblRezervacije() {
        return tblRezervacije;
    }

    public javax.swing.JButton getBtnPrikazi() {
        return btnPrikazi;
    }

    public javax.swing.JButton getBtnPromeni() {
        return btnPromeni;
    }

    public javax.swing.JTextArea getTxtAreaDetalji() {
        return txtAreaDetalji;
    }

    public javax.swing.JTable getTblStavke() {
        return tblStavke;
    }
}
