@startuml
skinparam backgroundColor white
skinparam shadowing false
skinparam monochrome true
skinparam sequenceMessageAlign center
hide footbox

participant "k:Controller" as K
participant "so:UbaciRegionSO" as SO
participant "r:RepositoryDbGeneric" as R

K -> SO : execute(Region)
activate SO

SO -> SO : precondition(Region)

alt naziv, kontinent i oznaka zadovoljavaju ograničenja
    SO -> R : connect()
    R --> SO : signal

    SO -> SO : executeOperation(Region)

    SO -> R : add(Region)
    R --> SO : signal

    SO -> R : commit()
    R --> SO : signal

    SO --> K : Region
else ograničenja nisu zadovoljena
    SO -> R : rollback()
    R --> SO : signal
    SO --> K : Exception("Систем не може да запамти регион")
end

deactivate SO

@enduml
