/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author mihajlo
 */
public class ServerAdminForm extends javax.swing.JFrame {

    /**
     * Creates new form ServerAdminForm
     */
    public ServerAdminForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuServer = new javax.swing.JMenu();
        miPokreniServer = new javax.swing.JMenuItem();
        miZaustaviServer = new javax.swing.JMenuItem();
        menuPodesavanja = new javax.swing.JMenu();
        miKonfiguracija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turistička agencija - Server");

        menuServer.setText("Server");

        miPokreniServer.setText("Pokreni server");
        miPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPokreniServerActionPerformed(evt);
            }
        });
        menuServer.add(miPokreniServer);

        miZaustaviServer.setText("Zaustavi server");
        miZaustaviServer.setEnabled(false);
        miZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZaustaviServerActionPerformed(evt);
            }
        });
        menuServer.add(miZaustaviServer);

        menuBar.add(menuServer);

        menuPodesavanja.setText("Podešavanja");

        miKonfiguracija.setText("Konfiguracija servera");
        miKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKonfiguracijaActionPerformed(evt);
            }
        });
        menuPodesavanja.add(miKonfiguracija);

        menuBar.add(menuPodesavanja);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPokreniServerActionPerformed
        try {
            Controller.getInstance().startServer();
            miPokreniServer.setEnabled(false);
            miZaustaviServer.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miPokreniServerActionPerformed

    private void miZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZaustaviServerActionPerformed
        try {
            Controller.getInstance().stopServer();
            miPokreniServer.setEnabled(true);
            miZaustaviServer.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miZaustaviServerActionPerformed

    private void miKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKonfiguracijaActionPerformed
        new ServerConfigForm(this, true).setVisible(true);
    }//GEN-LAST:event_miKonfiguracijaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuServer;
    private javax.swing.JMenuItem miPokreniServer;
    private javax.swing.JMenuItem miZaustaviServer;
    private javax.swing.JMenu menuPodesavanja;
    private javax.swing.JMenuItem miKonfiguracija;
    // End of variables declaration//GEN-END:variables
}
