/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import controller.Controller;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import threads.HandleClientThread;
import listeners.ServerListener;
import view.components.TableModelKlijent;

/**
 *
 * @author mihajlo
 */
public class ServerAdminForm extends javax.swing.JFrame implements ServerListener {

    private final TableModelKlijent modelKlijenti = new TableModelKlijent();
    private final SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

    /**
     * Creates new form ServerAdminForm
     */
    public ServerAdminForm() {
        initComponents();
        tblKlijenti.setModel(modelKlijenti);
        Controller.getInstance().setListener(this);
        azurirajStatus(Controller.getInstance().isServerRunning());
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnPokreniServer = new javax.swing.JButton();
        btnZaustaviServer = new javax.swing.JButton();
        pnlLog = new javax.swing.JPanel();
        scrollLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlKlijenti = new javax.swing.JPanel();
        scrollKlijenti = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuPodesavanja = new javax.swing.JMenu();
        miKonfiguracija = new javax.swing.JMenuItem();
        menuTema = new javax.swing.JMenu();
        miTemaLight = new javax.swing.JMenuItem();
        miTemaDark = new javax.swing.JMenuItem();
        miTemaIntelliJ = new javax.swing.JMenuItem();
        miTemaDarcula = new javax.swing.JMenuItem();
        miTemaMacLight = new javax.swing.JMenuItem();
        miTemaMacDark = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Туристичка агенција - Сервер");

        lblNaslov.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNaslov.setText("Туристичка агенција - Сервер");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("Сервер је угашен");

        btnPokreniServer.setText("Покрени сервер");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        btnZaustaviServer.setText("Заустави сервер");
        btnZaustaviServer.setEnabled(false);
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPokreniServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZaustaviServer)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaslov)
                    .addComponent(lblStatus)
                    .addComponent(btnPokreniServer)
                    .addComponent(btnZaustaviServer))
                .addContainerGap())
        );

        pnlLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Системске поруке"));

        txtLog.setEditable(false);
        txtLog.setRows(10);
        scrollLog.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollLog)
                .addContainerGap())
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollLog)
                .addContainerGap())
        );

        pnlKlijenti.setBorder(javax.swing.BorderFactory.createTitledBorder("Повезани клијенти"));

        scrollKlijenti.setViewportView(tblKlijenti);

        javax.swing.GroupLayout pnlKlijentiLayout = new javax.swing.GroupLayout(pnlKlijenti);
        pnlKlijenti.setLayout(pnlKlijentiLayout);
        pnlKlijentiLayout.setHorizontalGroup(
            pnlKlijentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlijentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollKlijenti)
                .addContainerGap())
        );
        pnlKlijentiLayout.setVerticalGroup(
            pnlKlijentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlijentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPodesavanja.setText("Подешавања");

        miKonfiguracija.setText("Конфигурација сервера");
        miKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKonfiguracijaActionPerformed(evt);
            }
        });
        menuPodesavanja.add(miKonfiguracija);

        menuBar.add(menuPodesavanja);

        menuTema.setText("Тема");

        miTemaLight.setText("FlatLaf Light");
        miTemaLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaLightActionPerformed(evt);
            }
        });
        menuTema.add(miTemaLight);

        miTemaDark.setText("FlatLaf Dark");
        miTemaDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaDarkActionPerformed(evt);
            }
        });
        menuTema.add(miTemaDark);

        miTemaIntelliJ.setText("FlatLaf IntelliJ");
        miTemaIntelliJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaIntelliJActionPerformed(evt);
            }
        });
        menuTema.add(miTemaIntelliJ);

        miTemaDarcula.setText("FlatLaf Darcula");
        miTemaDarcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaDarculaActionPerformed(evt);
            }
        });
        menuTema.add(miTemaDarcula);

        miTemaMacLight.setText("✔ FlatLaf macOS Light");
        miTemaMacLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaMacLightActionPerformed(evt);
            }
        });
        menuTema.add(miTemaMacLight);

        miTemaMacDark.setText("FlatLaf macOS Dark");
        miTemaMacDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTemaMacDarkActionPerformed(evt);
            }
        });
        menuTema.add(miTemaMacDark);

        menuBar.add(menuTema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKlijenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKonfiguracijaActionPerformed
        new ServerConfigForm(this, true).setVisible(true);
        azurirajStatus(Controller.getInstance().isServerRunning());
    }//GEN-LAST:event_miKonfiguracijaActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        if (!Controller.getInstance().isConfigurationValid()) {
            JOptionPane.showMessageDialog(this,
                    "Конфигурација сервера није потпуна. Молимо унесите URL, корисничко име и исправан порт кроз Конфигурација.",
                    "Упозорење", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Controller.getInstance().startServer();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        try {
            Controller.getInstance().stopServer();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnZaustaviServerActionPerformed

    private void miTemaLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaLightActionPerformed
        primeniTemu(new FlatLightLaf(), miTemaLight);
    }//GEN-LAST:event_miTemaLightActionPerformed

    private void miTemaDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaDarkActionPerformed
        primeniTemu(new FlatDarkLaf(), miTemaDark);
    }//GEN-LAST:event_miTemaDarkActionPerformed

    private void miTemaIntelliJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaIntelliJActionPerformed
        primeniTemu(new FlatIntelliJLaf(), miTemaIntelliJ);
    }//GEN-LAST:event_miTemaIntelliJActionPerformed

    private void miTemaDarculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaDarculaActionPerformed
        primeniTemu(new FlatDarculaLaf(), miTemaDarcula);
    }//GEN-LAST:event_miTemaDarculaActionPerformed

    private void miTemaMacLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaMacLightActionPerformed
        primeniTemu(new FlatMacLightLaf(), miTemaMacLight);
    }//GEN-LAST:event_miTemaMacLightActionPerformed

    private void miTemaMacDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTemaMacDarkActionPerformed
        primeniTemu(new FlatMacDarkLaf(), miTemaMacDark);
    }//GEN-LAST:event_miTemaMacDarkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPodesavanja;
    private javax.swing.JMenu menuTema;
    private javax.swing.JMenuItem miKonfiguracija;
    private javax.swing.JMenuItem miTemaDarcula;
    private javax.swing.JMenuItem miTemaDark;
    private javax.swing.JMenuItem miTemaIntelliJ;
    private javax.swing.JMenuItem miTemaLight;
    private javax.swing.JMenuItem miTemaMacDark;
    private javax.swing.JMenuItem miTemaMacLight;
    private javax.swing.JPanel pnlKlijenti;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollKlijenti;
    private javax.swing.JScrollPane scrollLog;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

    private static final String OZNAKA = "✔ ";

    private void primeniTemu(LookAndFeel laf, JMenuItem izabrana) {
        try {
            UIManager.setLookAndFeel(laf);
            FlatLaf.updateUI();
            oznaciIzabranuTemu(izabrana);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void oznaciIzabranuTemu(JMenuItem izabrana) {
        JMenuItem[] sve = {miTemaLight, miTemaDark, miTemaIntelliJ, miTemaDarcula, miTemaMacLight, miTemaMacDark};
        for (JMenuItem stavka : sve) {
            String tekst = stavka.getText().replace(OZNAKA, "");
            stavka.setText(stavka == izabrana ? OZNAKA + tekst : tekst);
        }
    }

    private void azurirajStatus(boolean pokrenut) {
        if (pokrenut) {
            lblStatus.setText("Сервер је покренут");
            lblStatus.setForeground(new java.awt.Color(0, 128, 0));
        } else {
            lblStatus.setText("Сервер је угашен");
            lblStatus.setForeground(java.awt.Color.RED);
        }
        btnPokreniServer.setEnabled(!pokrenut && Controller.getInstance().isConfigurationValid());
        btnZaustaviServer.setEnabled(pokrenut);
    }

    @Override
    public void onLog(String poruka) {
        SwingUtilities.invokeLater(() -> {
            txtLog.append("[" + sdf.format(new Date()) + "] " + poruka + "\n");
            txtLog.setCaretPosition(txtLog.getDocument().getLength());
        });
    }

    @Override
    public void onKlijentPovezan(HandleClientThread klijent) {
        SwingUtilities.invokeLater(() -> modelKlijenti.dodajKlijenta(klijent));
    }

    @Override
    public void onKlijentAzuriran(HandleClientThread klijent) {
        SwingUtilities.invokeLater(() -> modelKlijenti.azurirajKlijenta(klijent));
    }

    @Override
    public void onKlijentOdjavljen(HandleClientThread klijent) {
        SwingUtilities.invokeLater(() -> modelKlijenti.ukloniKlijenta(klijent));
    }

    @Override
    public void onPromenaStatusa(boolean pokrenut) {
        SwingUtilities.invokeLater(() -> azurirajStatus(pokrenut));
    }
}
